steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/flaskhelloworldapp1-442123/flaskhelloworldapp1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/flaskhelloworldapp1-442123/flaskhelloworldapp1']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'flaskhelloworldapp1', '--image', 'gcr.io/flaskhelloworldapp1-442123/flaskhelloworldapp1', '--region', 'us-central1', '--platform', 'managed', '--port', '80']

options:
  logging: GCS_BUCKET  # This will store logs in a Cloud Storage bucket
  logsBucket: 'gs://your-log-bucket'  # Specify your Cloud Storage bucket for logs
images:
  - gcr.io/flaskhelloworldapp1-442123/flaskhelloworldapp1
serviceAccount: 'your-service-account@your-project.iam.gserviceaccount.com'
